behaviors:
  Ball:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 48
      num_layers: 6
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5.0e15
    time_horizon: 64
    summary_freq: 100000